# Generated by Django 5.1.6 on 2025-03-31 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('ARTICLE_CREATED', 'Article Created'), ('ARTICLE_UPDATED', 'Article Updated'), ('ARTICLE_DELETED', 'Article Deleted'), ('COMMENT_CREATED', 'Comment Created'), ('COMMENT_UPDATED', 'Comment Updated'), ('COMMENT_DELETED', 'Comment Deleted')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
